### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by dallefeste**

### CODE REVIEW

**Comment by dulvui** [comment]
@dallefeste Thanks for the PR! There are some files without license, so the reuse check fails. Could you please add the license?

**Review by dallefeste — COMMENTED** [review]
I made it in the most files, probably the two png icons still need to be moved to cdn.

**Comment by dulvui** [comment]
@dallefeste Thank you! I saw that there are still some other files without license, but I'll fix it by my self and move the pngs to our CDN.
Just a question about the `local_modules/vue2-datepicker` directory: are this files created by you or is this the vue2-datepicker module? Because if its vue2-datepicker module, I think the correct License header would be the projects license, that would be MIT I think. In case I'll fix that too.

**Comment by dallefeste** [comment]
Thanks Simon. I confirm you that `local_modules/vue2-datepicker` directory contains a modified version of the vue2-datepicker module. I confirm also I use this component because of the MIT licence. I remain at your complete disposal.

**Pull request merged**
